### PR TITLE
Added `document` and `direct_shares` resources

### PR DESCRIPTION
**Pull request by marceloalmeida**
Added:
- `dynatrace_document` Resource and data resource - Allows to create documents (dashboards v2 and notebooks)
- `dynatrace_direct_shares` - Allow sharing documents with users and groups

### CODE REVIEW

**Review by alvaropalmeirao — APPROVED** [review]

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @marceloalmeida,
Let me know when your PR is ready from your point of view. I would then take a look at the new resources early next week.

**Comment by marceloalmeida** [comment]
> Hello @marceloalmeida, Let me know when your PR is ready from your point of view. I would then take a look at the new resources early next week.

Hi @Dynatrace-Reinhard-Pilz, the PR is ready for review, I've finished the developments and tested them end to end.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi @marceloalmeida ,

I need to ask for a bit more patience until I'm merging in your PR. We're in the process of migrating several resources over to utilize a shared HTTP Client. The resource you've implemented will also be affected.

There's are no further actions required from your side. I'm planning to make the necessary modifications on top of your PR. But it will take another week or two until we can release with that shared HTTP Client.

thanks for your patience,
Reinhard

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @marceloalmeida,

Your PR will be included in the upcoming release. I'm just working on a few finishing touches.
There's one question I cannot answer after reviewing the resource `dynatrace_document`: You've included the attribute `actor` as an optional. I'm unable to correlate that to any functionality. Neither the REST API nor the WebUI allow for setting such an actor. Where did you stumble across that?

I've also made a small modification regarding the `owner` attribute. It is flagged as `optional` AND `computed` now. That allows you to omit code like
```
ifecycle {
   ignore_changes = [
     owner
   ]
}
```
in your modules in case you haven't specified an owner at all.

**Pull request merged**
